### ISSUE TITLE
NOMS site page views data pull

### ISSUE THREAD

**Issue by wdwatkins** [usgs-makerspace/analytics_pipeline#43]
NOMS wants to ingest pageviews of site pages for one of their Tableau dashboards.  We can provide the data by setting up a data pull and pushing the data to S3.

 The main deliverable is a daily data pull (of yesterday's data) that generates a daily file with of a column of site id and unique pageviews that we store somewhere in S3.  This code should provide a good basis for the initial GA data pull: https://code.usgs.gov/wwatkins/ad_hoc_analytics/-/blob/master/nwis_web_hit_count_2020/nwis_site_pages.R  That is just looking for 8 or 15-digit site IDs in the URL—I think Shawna has a more precise regex, so talk to her first.  You would just need to extract the site number from the URL after that.  The old site pages have very complicated URLs so might be fussy.  The new monitoring location pages should be easy.  Its ok if there is some imprecision in the pattern-matching with the ugly URLs, the end use here is mostly an order of magnitude kind of thing.

You can probably borrow most of the Jenkins job and container from the existing pull in this repo.  The Google Analytics credentials are the same as used in other repos (e.g. the GWSIP report)

Chuck Hansen is our contact with NOMS for where in S3 we should push the data.  

 - [ ] daily data pull (of yesterday's data) that generates a daily file with of a column of site id and unique pageviews that we store somewhere in S3
 - [ ] Separate of the scheduled job, run the pull for each day starting in 2020 so we have a bit of a baseline record.

**Comment by wdwatkins** [comment]
I know I wrote that test code in R, but if you would rather write this in Python that would be ok too.  You would need to figure out the Google Analytics client though.

**Comment by mhines-usgs** [comment]
Finally going to start on this today. I also have a meeting with Shawna later for something else and will see if she has a few minutes to chat about this and point me at some code.

**Comment by wdwatkins** [comment]
Yeah that makes sense.

**Comment by mhines-usgs** [comment]
throwing this here from email 
We should drop the site_no part of our regex.  We might want to also drop the [^0-9] ​unless you can also make that accept the end of the string.  I think that right now it would miss if the site number is the end of the URL.  If we do that, I think the 15 digit filter becomes redundant.  
It's not worth getting too worried about precision here, since 1) A lot of the issues go away when the new monitoring location pages become default (I think some time this year?) and 2) A 90% accurate number ought to be fine here, that is enough to tell a data chief which sites are used more than others.  If there is minimal difference between methods, we can just go with whatever is simpler, and make sure we communicate the fuzziness to consumers of this.

**Comment by mhines-usgs** [comment]
i merged in all the changes on the noms-daily branch and just had success running it for yesterday

created a jenkins job from the jenkinsfile here https://jenkins.wma.chs.usgs.gov/job/MakerSpace/view/analytics/job/noms_daily/
dumps the data into s3 here s3://wma-analytics-data/noms/test/parquet/ (currently set by default to run nightly on test tier)

put a pull request here for the athena table addition to the existing analytics database https://code.chs.usgs.gov/ctek/applications/iidd/data-science/athena-analytics/-/merge_requests/2

**Comment by wdwatkins** [comment]
Looks good, can we just make the S3 folder named something less project-specific like 'monitoring_location_pages'?  We'll likely use this data for other purposes, and `noms` might not be meaningful in a few years whenever that project winds down.

**Comment by mhines-usgs** [comment]
sure, that's fine. do you think the athena table name is ok as noms specific?

**Comment by wdwatkins** [comment]
If that is the name that shows up in Tableau, I suppose its ok either way since they will likely be consuming it.  If its simple to change at this point though it might be nice to keep it consistent.

**Comment by mhines-usgs** [comment]
yeah, let me do a sweep through and change things now before we get too far in! 🧹

**Comment by mhines-usgs** [comment]
should be good to go now, everything is noms-free!

**Comment by mhines-usgs** [comment]
i merged in the changes for the database in cloudformation, however analytics-test is still not generated by the cloudformation template yet, so i created it manually from the data source for the moment so that i could finish the full workflow and create the tableau resources. according to ivan i just have to make the proper pull request. but at this point there is a published data source on both the internal (https://tableau.chs.usgs.gov/#/datasources/5339?:origin=card_share_link) and external/internal-only facing  (https://tableau.usgs.gov/#/site/InternalGuestAccess/datasources/139681) tableau servers that will refresh nightly from the updated s3 output, triggered by the jenkins job. 

on the internal only tableau server i added a summary table but it's too much data and is very slow at least for me (https://tableau.chs.usgs.gov/views/AnalyticsDashboardExploration-Embedded/MonitoringLocationPagesUniquePageviewsDashboard?:origin=card_share_link&:embed=n), but I was wondering if you wanted me to spend some time creating a few simple views of this data that could be included on the EC Dashboard. Something like what was described here with top 10 lists for different time frames? https://trello.com/c/DaklCLK9/16-10-as-an-iow-product-owner-i-want-to-see-top-ten-list-of-top-sites-overall-top-monitoring-locations-sites-top-network-sites-etc

**Comment by mhines-usgs** [comment]
cool, I think putting together a view where you could toggle between a few views like last week/month/year etc would only take a few hours. I can reach out to them and ask and share the access to the tables. 

I'm glad that view is working! It could have just been tableau server's behavior or my connection at the time! 

should I also share the published Tableau sources with Jeff or do you want to do that to have him and Branden access them?

**Comment by wdwatkins** [comment]
Go ahead and share with the NOMS group.

**Comment by mhines-usgs** [comment]
sent along some emails to both groups and already got a response from Chuck! 🚀

**Comment by wdwatkins** [comment]
Just a few little things and then we can close this issue:

- [ ] Instead of `Sys.Date() - 1` to get `yesterday`, use `as.Date(Sys.time(), tz = 'America/New_York') - 1`. This ensures that we don't end up hitting the window where its tomorrow UTC but today in the US.  This shouldn't affect current output since the job runs at 7 UTC, but is just safer in case we change that.
- [ ] Switch the scheduled job so it is building on the prod tier instead of test.  Does this involve changing the CloudFormation for Athena?  I see that uses an environment variable for the tier.  We can just keep the test tier for testing new code. 
 If the FY20 data you pulled is also in test, just copy that over to the prod S3 folder.  (We should do this at some point for the dashboard data pull too, but don't need to worry about that now).
- [ ] Cut a release from this repo and build from that on the scheduled job instead of master

**Comment by mhines-usgs** [comment]
thanks, i will wrap these up in the AM!

**Comment by mhines-usgs** [comment]
new production athena branch https://code.chs.usgs.gov/ctek/applications/iidd/data-science/athena-analytics/-/tree/production
and athena_production is out on aws prod account now, along with athena_qa. both of those db will just have the data for this new table at this point. whenever it matters we can catch everything up.

new release https://github.com/usgs-makerspace/analytics_pipeline/releases/tag/v0.0.7

will go fiddle with jenkins settings now and test it out

**Comment by wdwatkins** [comment]
Can you also add a short blurb to the readme on how to run the script manually specifying the date (i.e. if the Jenkins job fails, so we could fill in a  missed day if needed)?

**Comment by mhines-usgs** [comment]
ah shoot, it's going to the wrong path on aws s3, prod not production (which is dictated by the cloudformation upstream job, lol). so.. that jenkinsfile will needs a tweak, and new release sob. it's ok. we have lots of numbers to use.

**Comment by mhines-usgs** [comment]
so yeah, the database we create with cloudformation in supposedly the correct way, doesn't seem to work with Tableau server. working with Ivan we added a few other parameters that we saw in test (how was test made? do you have the cloudformation file or any memory of it?) I don't see it listed in the stacks there so I assume maybe it was made another way? 

But when seeing that error on screen on Tableau server, this is popping up under the hood, so seems like permission/user related. ugh.

ErrorType: "Unknown", RedirectUrl: null,…}
ErrorMessage: "An error occurred while communicating with the Amazon Athena data source 'federated.1mvzwp80ujfmyk12uuibl1yv7euw' Unable to connect to the server. Check that the server is running and that you have access privileges to the requested database.\n[Simba][JDBC](11380) Null pointer exception.\nThe table \"[analytics_qa].[monitoring_location_pages_daily_data]\" does not exist.\nUnable to connect to the Amazon Athena server \"athena.us-west-2.amazonaws.com\". Check that the server is running and that you have access privileges to the requested database.\nDataServiceFailure\nThere was an error with the data source \"monitoring_location_pages_daily_data (analytics_qa)\". Verify that the data source is configured correctly.<br>2021-06-10 22:28:58.930, (YMKSKuTn5ER8QHVmRgB-zwAAARo,1:0)"
ErrorType: "Unknown"
RedirectUrl: null
errorResponseType: "DataSourceConnectionAttempt"

**Comment by mhines-usgs** [comment]
i guess what I'll do, if you agree this is the best course for now, is try to manually re-create this table on production and see if it works. then if not, maybe delete it and recreate from the console. if that does work, I can keep working with CHS with troubleshooting QA as long as they're willing, and can at least pass the prod tier on to Chuck et al even if it's not quite all set yet.

it's super odd, like I said, because my desktop is OK connecting to the athena db/table, and shows data. i'm connecting using the athena keys but then after I publish the data connection to athena with those credentials embedded, that's where the error pops up. yet if i go to tableau server and test the connection there, it says test succeeded. hah. it seems like this is somehow the reverse experience I was having a year ago or so, where my desktop would fail when I used those credentials but it worked after being published to tableau server. 🤯

**Comment by mhines-usgs** [comment]
another weird thing i just tested and shared with chs tech support person, was that the same athena resources published to the tableau.chs.usgs.gov server instead of tableau.usgs.gov server work fine.

**Comment by wdwatkins** [comment]
> so yeah, the database we create with cloudformation in supposedly the correct way, doesn't seem to work with Tableau server. working with Ivan we added a few other parameters that we saw in test (how was test made? do you have the cloudformation file or any memory of it?) I don't see it listed in the stacks there so I assume maybe it was made another way?

I think I would have previously done this by manually uploading a cloudformation json in the console ( I never had credentials/other sorted out the command line submission, or worked with the ctek deployment).

> i guess what I'll do, if you agree this is the best course for now, is try to manually re-create this table on production and see if it works. then if not, maybe delete it and recreate from the console. if that does work, I can keep working with CHS with troubleshooting QA as long as they're willing, and can at least pass the prod tier on to Chuck et al even if it's not quite all set yet.

If the manual creation works, and it is a rabbit hole to keep troubleshooting, we can call that ok for now.  It would be good to tie this off.

**Comment by mhines-usgs** [comment]
unfortunately no matter how it's published it's failing, in contacting the person Ben @ CHS through tickets, we both are thinking it's a driver issue with Tableau server. there is an upgrade planned tonight and he is hoping it fixes itself.. but I'll test again in the morning. If it's not working he agreed with work with Tableau with a support ticket, since I have now way to access any tableau server logs or anything useful between tableau server and CHS/Athena.

**Comment by mhines-usgs** [comment]
![image](https://user-images.githubusercontent.com/6920344/122426833-2fbd3c00-cf56-11eb-86e1-89eb08c4f1de.png)

**Comment by wdwatkins** [comment]
That's frustrating.  So is it only existing tables (i.e. for the dashboard) that work right now?

**Comment by wdwatkins** [comment]
Thinking back now, I was remembering using cloudformation for the Athena tables for natweb server logs, and we've never used those in Tableau.  So those are probably not relevant :(  We probably created the dashboard tables using manual SQL, but I don't think that is allowed anymore on the production VPC?  That might be a workaround if someone can turn it back on, unless its just some change that happened since we built the dashboard.

**Comment by mhines-usgs** [comment]
Yeah, unfortunately nothing works at all for making new connections on that server, it's not Athena specific or anything we're doing. Which is the most awful part.

**Comment by wdwatkins** [comment]
What is the other connection that works?  Internal vs external tableau?

**Comment by mhines-usgs** [comment]
Yep, internal is fine.

**Comment by mhines-usgs** [comment]
Good news, after they did the server upgrade last Thursday night, everything works fine! 🤷‍♀️ 'final' published internal-production data source https://tableau.usgs.gov/#/site/InternalGuestAccess/datasources/142999. I'll share it's details along to the CA group too.
